repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        exclude: ^store_api/migrations|django_api/settings
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort