version: '3'
services:
  db:
    image: "postgres:16"
    environment:
      - POSTGRES_USER=store
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=store
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
