# Generated by Django 5.1.1 on 2024-09-23 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0002_alter_user_deleted_alter_user_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAPIToken',
            fields=[
                ('token', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expiry', models.DateTimeField(editable=False)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
