# Generated by Django 5.1.1 on 2024-10-18 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_api", "0004_product_owner_user_alter_productstock_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="owner_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
