# Generated by Django 5.1.3 on 2024-11-21 16:52

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_api", "0006_alter_product_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
                ("deleted", models.DateTimeField(null=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(to="store_api.tag"),
        ),
    ]
