# Generated by Django 5.1.3 on 2025-01-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store_api", "0007_tag_product_tags"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productstock",
            name="store_api_productstock_reserved_gte_zero",
        ),
        migrations.RemoveConstraint(
            model_name="productstock",
            name="store_api_productstock_sold_gte_zero",
        ),
        migrations.RemoveField(
            model_name="productstock",
            name="reserved",
        ),
        migrations.RemoveField(
            model_name="productstock",
            name="sold",
        ),
    ]
