# Generated by Django 5.2a1 on 2025-01-29 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_api", "0009_order_product_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="order",
        ),
        migrations.CreateModel(
            name="OrderLineItem",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "order_id",
                        "product_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("variant", models.CharField()),
                ("quantity", models.IntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="store_api.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="store_api.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                through="store_api.OrderLineItem", to="store_api.product"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderlineitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="store_api_orderlineitem_quantity_gt_zero",
            ),
        ),
    ]
