# Generated by Django 5.2a1 on 2025-02-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "store_api",
            "0010_remove_product_order_orderlineitem_order_products_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["created"], name="store_api_order_created"),
        ),
    ]
