# Generated by Django 5.2a1 on 2025-02-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_api", "0012_alter_order_created_alter_order_state_and_more"),
    ]

    operations = [
        migrations.DeleteModel("OrderLineItem"),
        migrations.CreateModel(
            name="OrderLineItem",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "order_id",
                        "product_id",
                        "variant",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("variant", models.CharField()),
                ("quantity", models.IntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=models.deletion.DO_NOTHING,
                        to="store_api.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=models.deletion.DO_NOTHING,
                        to="store_api.product",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="orderlineitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="store_api_orderlineitem_quantity_gt_zero",
            ),
        ),
    ]
