version: "3"
services:
  postgres:
    image: postgres:14.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: kata
      POSTGRES_PASSWORD: kata
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./docker_data/psql/data:/var/lib/postgresql/data